import { CLOUDFLARE_API_KEY, GLM_WORKER_URL } from '@/lib/env';
import { SYSTEM_PROMPT } from './prompts';
import { getAllTools } from './tools';
import prisma from '@/lib/prisma';
import { MESSAGE_ROLE } from '@/generated/prisma/enums';
import { zodToJsonSchema } from 'zod-to-json-schema';

/**
 * Interface for messages sent to/from the LLM.
 * Supports standard roles and tool-calling metadata.
 */
interface Message {
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string | null;
  tool_call_id?: string;
  tool_calls?: unknown[];
  name?: string;
}

/**
 * Main function to handle streaming text responses from the GLM-4.7-Flash model.
 * It manages tool execution loops, Server-Sent Events (SSE) parsing, and database persistence.
 *
 * @param messages - The history of messages in the conversation.
 * @param userId - The ID of the user for tool scoping and message ownership.
 */
export async function streamText(
  messages: { role: string; content: string; parts?: unknown[] }[],
  userId: string,
) {
  // Retrieve all registered tools for this user
  const tools = getAllTools(userId);

  /**
   * Convert Zod-based tools into the JSON schema format expected by GLM-4.7-Flash.
   * We use 'zod-to-json-schema' to automatically generate these schemas from our tool definitions.
   */
  const formattedTools = Object.entries(tools).map(([name, tool]) => {
    return {
      type: 'function',
      function: {
        name,
        description: tool.description,
        parameters: zodToJsonSchema(tool.parameters),
      },
    };
  });

  /**
   * Pre-process incoming messages for the LLM.
   * Handles parts-based content and ensures compatibility with the chat completion endpoint.
   */
  const chatMessages: Message[] = [
    { role: 'system', content: SYSTEM_PROMPT },
    ...messages.map((m: any) => {
      // eslint-disable-line @typescript-eslint/no-explicit-any
      let content = m.content;
      // Extract text from parts if the UI sends a complex message structure
      if (Array.isArray(m.parts)) {
        content = m.parts
          .map((p: any) => (p as any).text || (p as any).reasoning || '')
          .join(''); // eslint-disable-line @typescript-eslint/no-explicit-any
      } else if (typeof m.content === 'object' && m.content !== null) {
        content = JSON.stringify(m.content);
      }
      return {
        role: m.role,
        content: content || '',
        tool_calls: m.tool_calls,
        tool_call_id: m.tool_call_id,
        name: m.name,
      };
    }),
  ];

  const encoder = new TextEncoder();

  /**
   * Create a ReadableStream to pipe AI output back to the client in real-time.
   */
  const stream = new ReadableStream({
    async start(controller) {
      const currentMessages: Message[] = [...chatMessages];

      let iteration = 0;
      const maxIterations = 5; // Prevent infinite tool-calling loops

      // Track parts generated by the assistant for eventual database storage
      const assistantParts: any[] = []; // eslint-disable-line @typescript-eslint/no-explicit-any

      try {
        while (iteration < maxIterations) {
          iteration++;

          // Call the custom GLM Worker proxy
          const response = await fetch(GLM_WORKER_URL!, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${CLOUDFLARE_API_KEY}`,
            },
            body: JSON.stringify({
              messages: currentMessages,
              tools: formattedTools,
              tool_choice: 'auto',
              stream: true,
            }),
          });

          if (!response.ok) {
            const errorText = await response.text();
            controller.enqueue(
              encoder.encode(`3:${JSON.stringify(errorText)}\n`),
            );
            controller.close();
            return;
          }

          const reader = response.body!.getReader();
          const decoder = new TextDecoder();
          let fullTurnContent = '';
          let turnToolCalls: {
            id: string;
            type: string;
            function: { name: string; arguments: string };
          }[] = [];
          const tcArgsBuffer: string[] = [];
          let lineBuffer = '';
          let turnHadReasoning = false;

          /**
           * Inner loop to read the stream from the model turn by turn.
           */
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            const chunk = decoder.decode(value, { stream: true });
            lineBuffer += chunk;

            // Re-assemble lines from the stream chunk
            const lines = lineBuffer.split('\n');
            lineBuffer = lines.pop() || '';

            for (const line of lines) {
              const trimmedLine = line.trim();
              if (
                trimmedLine.startsWith('data: ') &&
                trimmedLine !== 'data: [DONE]'
              ) {
                try {
                  const data = JSON.parse(trimmedLine.slice(6));
                  // Metadata chunks (like usage) might not have 'choices'. Use optional chaining.
                  const delta = data.choices?.[0]?.delta;
                  if (!delta) continue;

                  /**
                   * Handle Reasoning Content (Thinking Process).
                   * Some models emit a 'reasoning_content' or 'thought' field.
                   */
                  const reasoning =
                    delta.reasoning_content || delta.thought || delta.thinking;
                  if (reasoning) {
                    turnHadReasoning = true;
                    const reasoningPart = {
                      type: 'reasoning',
                      reasoning: reasoning,
                      isStreaming: true,
                    };
                    // Code 'b' signals an update to the 'parts' of a message in the UI
                    controller.enqueue(
                      encoder.encode(`b:${JSON.stringify(reasoningPart)}\n`),
                    );

                    // Accumulate reasoning for persistent storage
                    const lastPart = assistantParts[assistantParts.length - 1];
                    if (lastPart?.type === 'reasoning') {
                      (lastPart.reasoning as string) += reasoning;
                    } else {
                      assistantParts.push({
                        ...reasoningPart,
                        isStreaming: false,
                      });
                    }
                  }

                  /**
                   * Handle Standard Text Content.
                   */
                  if (delta.content) {
                    // If the model was in 'reasoning' mode, end it before starting visible text
                    if (turnHadReasoning) {
                      turnHadReasoning = false;
                      controller.enqueue(
                        encoder.encode(
                          `b:${JSON.stringify({ type: 'reasoning', isStreaming: false })}\n`,
                        ),
                      );
                    }

                    fullTurnContent += delta.content;

                    // Code '0' is the standard Vercel AI SDK code for text delta
                    controller.enqueue(
                      encoder.encode(`0:${JSON.stringify(delta.content)}\n`),
                    );

                    // Code 'b' ensures parts-based UIs (rendered as bubble message segments) stay synced
                    const textPart = { type: 'text', text: delta.content };
                    controller.enqueue(
                      encoder.encode(`b:${JSON.stringify(textPart)}\n`),
                    );

                    // Accumulate text for persistent storage
                    const lastPart = assistantParts[assistantParts.length - 1];
                    if (lastPart?.type === 'text') {
                      (lastPart.text as string) += delta.content;
                    } else {
                      assistantParts.push({ ...textPart });
                    }
                  }

                  /**
                   * Handle Tool Call initialization and argument streaming.
                   */
                  if (delta.tool_calls) {
                    if (turnHadReasoning) {
                      turnHadReasoning = false;
                      controller.enqueue(
                        encoder.encode(
                          `b:${JSON.stringify({ type: 'reasoning', isStreaming: false })}\n`,
                        ),
                      );
                    }

                    for (const tc of delta.tool_calls) {
                      const idx = tc.index;
                      if (!turnToolCalls[idx]) {
                        turnToolCalls[idx] = {
                          id: tc.id,
                          type: 'function',
                          function: { name: tc.function?.name, arguments: '' },
                        };
                        tcArgsBuffer[idx] = '';
                      }
                      if (tc.function?.arguments) {
                        tcArgsBuffer[idx] += tc.function.arguments;
                      }
                    }
                  }
                } catch (e) {
                  console.error('Error parsing SSE line:', trimmedLine, e);
                }
              }
            }
          }

          // Cleanup: Ensure reasoning is marked as finished if the turn ends abruptly
          if (turnHadReasoning) {
            controller.enqueue(
              encoder.encode(
                `b:${JSON.stringify({ type: 'reasoning', isStreaming: false })}\n`,
              ),
            );
          }

          // Finish re-constructing the tool calls with full arguments
          turnToolCalls = turnToolCalls.filter(Boolean).map((tc, idx) => ({
            ...tc,
            function: { ...tc.function, arguments: tcArgsBuffer[idx] },
          }));

          const assistantMsg: Message = {
            role: 'assistant',
            content: fullTurnContent || null,
            tool_calls: turnToolCalls.length > 0 ? turnToolCalls : undefined,
          };
          currentMessages.push(assistantMsg);

          /**
           * If tool calls were requested, execute them and feed results back to the model.
           */
          if (turnToolCalls.length > 0) {
            for (const tc of turnToolCalls) {
              const toolName = tc.function.name;
              let args = {};
              try {
                args = JSON.parse(tc.function.arguments);
              } catch (e) {
                void e;
                console.error(
                  'Failed to parse tool args:',
                  tc.function.arguments,
                );
              }

              // UI Sync: Notify client that a tool has started execution
              const callPart = {
                type: `tool-${toolName}`,
                state: 'input-available',
                input: args,
                toolCallId: tc.id,
              };
              controller.enqueue(
                encoder.encode(`b:${JSON.stringify(callPart)}\n`),
              );

              // Log this "part" for the final assistant message record
              assistantParts.push({ ...callPart });

              const tool = tools[toolName];
              if (tool) {
                try {
                  // Execute the actual logic (DB operations, etc.)
                  const result = await tool.execute(args);

                  // UI Sync: Notify client that tool execution succeeded
                  const resultPart = {
                    type: `tool-${toolName}`,
                    state: 'output-available',
                    output: result,
                    toolCallId: tc.id,
                  };
                  controller.enqueue(
                    encoder.encode(`b:${JSON.stringify(resultPart)}\n`),
                  );

                  // Update the part in our buffer
                  const partIdx = assistantParts.findIndex(
                    (p) => p.toolCallId === tc.id,
                  );
                  if (partIdx !== -1) {
                    assistantParts[partIdx] = {
                      ...assistantParts[partIdx],
                      ...resultPart,
                    };
                  }

                  // Add the tool result to the conversation for the next model iteration
                  currentMessages.push({
                    role: 'tool',
                    tool_call_id: tc.id,
                    name: toolName,
                    content: JSON.stringify(result),
                  });
                } catch (e: any) {
                  // eslint-disable-line @typescript-eslint/no-explicit-any
                  // Handle and stream tool execution errors
                  const errorResult = { success: false, error: e.message };
                  const errorPart = {
                    type: `tool-${toolName}`,
                    state: 'output-error',
                    errorText: e.message,
                    toolCallId: tc.id,
                  };
                  controller.enqueue(
                    encoder.encode(`b:${JSON.stringify(errorPart)}\n`),
                  );

                  const partIdx = assistantParts.findIndex(
                    (p) => p.toolCallId === tc.id,
                  );
                  if (partIdx !== -1) {
                    assistantParts[partIdx] = {
                      ...assistantParts[partIdx],
                      ...errorPart,
                    };
                  }

                  currentMessages.push({
                    role: 'tool',
                    tool_call_id: tc.id,
                    name: toolName,
                    content: JSON.stringify(errorResult),
                  });
                }
              }
            }
            // The continue keyword isn't needed here, let it loop for next iteration
          } else {
            /**
             * Final Stop Condition: The model generates text without requesting more tools.
             */

            // Persist the full assistant message (with all parts) to the database before closing
            if (assistantParts.length > 0) {
              try {
                await prisma.message.create({
                  data: {
                    userId: userId,
                    role: MESSAGE_ROLE.assistant,
                    parts: assistantParts,
                  },
                });
              } catch (dbErr) {
                console.error('Failed to persist assistant message:', dbErr);
              }
            }

            // End turn and send stop metadata (Code 'd')
            controller.enqueue(
              encoder.encode(
                `d:{"finishReason":"stop","usage":{"promptTokens":0,"completionTokens":0}}\n`,
              ),
            );
            controller.close();
            return;
          }
        }
      } catch (err: any) {
        // eslint-disable-line @typescript-eslint/no-explicit-any
        // Enforce error streaming if something goes wrong in the outer execution block
        controller.enqueue(
          encoder.encode(`3:${JSON.stringify(err.message)}\n`),
        );
        controller.close();
      }
    },
  });

  return {
    /**
     * Helper to wrap the stream in a standard text/plain Response compatible with Vercel AI SDK.
     */
    toUIMessageStreamResponse: (options?: any) => {
      // eslint-disable-line @typescript-eslint/no-explicit-any
      void options;
      return new Response(stream, {
        headers: {
          'Content-Type': 'text/plain; charset=utf-8',
          'x-vercel-ai-data-stream': 'v1',
        },
      });
    },
  };
}
